### ISSUE TITLE
Separate fetch a kernel repository from merge?

### ISSUE THREAD

**Issue by danghai** [CKI-project/skt#339]
I am just curious about why skt does not split the `cmd_merge` into `cmd_fetch` and `cmd_merge` for clear. Logically, at the beginning, we do not have anything. Then, we need to fetch , and checkout the kernel repository. I feel we cannot merge when we do not have any kernel source. And then, we have a `cmd_merge` for a separate stage to merge the kernel patch. 
`git` is an example. We cannot use `git-merge` to fetch and checkout directory.

**Comment by veruu** [comment]
What problem exactly would splitting of the stage solve?

Let's say we do it, and have a `skt clone` and `skt merge` commands. Why would they be better or more useful than using `git` commands in this case, and why would it be more comfortable to use two commands instead of a single one?

> git is an example. We cannot use git-merge to fetch and checkout directory.

This sounds more like a naming issue, rather then a reason to split the stages. If you do have a name that you feel is more appropriate, feel free to open a pull/issue to gather opinions on it. The docs for `git merge` say `Join two or more development histories together` which is exactly what `skt merge` does - joins an upstream repository with chosen branches/patches from elsewhere.
